name: Deploy Lambda

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup AWS CLI
      working-directory: terraform
      run: terraform init -backend-config="bucket=bucket-tfstates-postech-fiap-6soat" -backend-config="key=lambda.tfstate" -backend-config="region=us-east-1"
    
    - name: Terraform Plans
      working-directory: terraform
      run: terraform plan -out=tfplan
    
    - name: Apply Terraform
      working-directory: terraform
      run: terraform apply -input=false -auto-approve tfplan
    
  aws_cli_:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Zip Lambda function
      working-directory: lambda
      run: zip -r lambda.zip *
    
    - name: Verify if the zip file exists
      run: test -f lambda.zip && echo "Arquivo encontrado" || echo "Arquivo não encontrado"
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
    
    - name: Upload to S3
      run: aws s3 cp lambda.zip s3://bucket-tfstates-postech-fiap-6soat/lambda.zip